import { incentivos3IconSet } from "../incentivos3.util";

export const calculadoraConfig = {
  vars: [
    {
      id: 'car',
      des: 'Cartera',
      icon: incentivos3IconSet.car,
      format: 'number',
      key: 'v_car',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      show: false
    },
    {
      id: 'gru',
      des: 'Grupos',
      icon: incentivos3IconSet.gru,
      format: 'number',
      key: 'v_gru',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      show: false
    },
    {
      id: 'cli',
      des: 'Clientes',
      icon: incentivos3IconSet.cli,
      format: 'number',
      key: 'v_cli',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      show: false
    },
    {
      id: 'pagop',
      des: 'Pago Puntual',
      icon: incentivos3IconSet.pagop,
      format: 'percent',
      key: 'v_pagop',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      show: false
    },
    {
      id: 'efec1',
      des: 'Efect. -30 a 0 días',
      icon: incentivos3IconSet.efec1,
      format: 'percent',
      key: 'v_efec1',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      tp1: 0,
      tp2: 0,
      tp3: 0,
      show: false
    },
    {
      id: 'efec2',
      des: 'Efect. 1 a 30 días',
      icon: incentivos3IconSet.efec2,
      format: 'percent',
      key: 'v_efec2',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      show: false
    },
    {
      id: 'efec3',
      des: 'Efect. 31 a 60 días',
      icon: incentivos3IconSet.efec3,
      format: 'percent',
      key: 'v_efec3',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      show: false
    },
    {
      id: 'sc1',
      des: 'Supervision C1',
      icon: incentivos3IconSet.sc1,
      format: 'number',
      key: 'v_sc1',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      show: false
    },
    {
      id: 'acom',
      des: '% Asesores Comisionan',
      icon: incentivos3IconSet.acom,
      format: 'number',
      key: 'v_acom',
      bob: 0,
      bop: 0,
      met: 0,
      val: 0,
      show: false
    }
  ],
  plus: [
    {
      id: 'prod',
      des: 'Productividad',
      icon: incentivos3IconSet.prod,
      format: 'number',
      key: 'p_prod',
      val: 0,
      met: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    },
    {
      id: 'rop',
      des: 'Riesgo Ope.',
      icon: incentivos3IconSet.rop,
      format: 'number',
      key: 'p_rop',
      val: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    },
    {
      id: 'clim',
      des: 'Clima',
      icon: incentivos3IconSet.clim,
      format: 'number',
      key: 'p_clim',
      val: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    },
    {
      id: 'clib',
      des: 'Bancarización',
      icon: incentivos3IconSet.clib,
      format: 'number',
      key: 'p_clib',
      val: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    },
    {
      id: 'ret',
      des: 'Retención',
      icon: incentivos3IconSet.ret,
      format: 'percent',
      key: 'p_ret',
      val: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: false
    },
    {
      id: 'tas',
      des: 'Tasas',
      icon: incentivos3IconSet.tas,
      format: 'percent',
      key: 'p_tas',
      val: 0,
      val1: 0,
      diff: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    },
    {
      id: 'rot',
      des: 'Rotación',
      icon: incentivos3IconSet.rot,
      format: 'number',
      key: 'p_rot',
      val: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    },
    {
      id: 'sis',
      des: 'Sistemática',
      icon: incentivos3IconSet.sis,
      format: 'number',
      key: 'p_sis',
      val: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    },
    {
      id: 'tgru',
      des: 'Tamaño Grupos',
      icon: incentivos3IconSet.tgru,
      format: 'number',
      key: 'p_tgru',
      val: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    },
    {
      id: 'areu',
      des: 'Asistencia Reuniones',
      icon: incentivos3IconSet.areu,
      format: 'number',
      key: 'p_areu',
      val: 0,
      bos: 0,
      enab: false,
      show: false,
      sum: true
    }
  ],
  bob: 0,
  bop: 0,
  bos: 0,
  bot: 0,
  act: 0,
  mar_ren: 0,
  cla: 0
}